apps += Elisa::App
app_headers += apps/elisa/app.h

app_objs += $(addprefix apps/elisa/,\
  app.o\
)

i18n_files += $(addprefix apps/elisa/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
)

# tests += $(addprefix apps/elisa/test/,\
#   calculation_store.cpp\
# )

app_images += apps/elisa/elisa_icon.png
